import { NextRequest, NextResponse } from 'next/server'
import { GoogleGenerativeAI } from '@google/generative-ai'
import { extractText } from 'unpdf'
import { getAdminClient } from '@/lib/supabase'
export const runtime='nodejs'
export async function POST(request:NextRequest){
 const {applicationId}=await request.json();if(!applicationId)return NextResponse.json({error:'applicationId required'},{status:400});const db=getAdminClient()
 const {data:app,error}=await db.from('applications').select('*, candidates(*), jobs(*)').eq('id',applicationId).single();if(error||!app)return NextResponse.json({error:error?.message||'Application not found'},{status:404});if(!app.candidates?.resume_url)return NextResponse.json({error:'Candidate has no PDF resume'},{status:400})
 try{let buffer:ArrayBuffer;if(String(app.candidates.resume_url).startsWith('/api/files/')){const storagePath=String(app.candidates.resume_url).replace('/api/files/','').split('/').map(decodeURIComponent).join('/');const {data:file,error:fileError}=await db.storage.from('hr-files').download(storagePath);if(fileError||!file)throw new Error(fileError?.message||'Resume not found');buffer=await file.arrayBuffer()}else{const pdf=await fetch(app.candidates.resume_url,{cache:'no-store'});if(!pdf.ok)throw new Error('Resume could not be downloaded. Upload it again.');buffer=await pdf.arrayBuffer()}const extracted=await extractText(new Uint8Array(buffer),{mergePages:true});const text=String(extracted.text);const ai=new GoogleGenerativeAI(process.env.GEMINI_API_KEY||'').getGenerativeModel({model:'gemini-3.1-flash-lite'});const prompt=`Analise o currículo para a vaga abaixo. Responda SOMENTE JSON válido: {"summary":"resumo profissional em português","score":0,"reason":"justificativa curta em português"}. Não invente dados. VAGA: ${app.jobs.title}\n${app.jobs.description}\nCURRÍCULO:\n${text.slice(0,30000)}`;const result=await ai.generateContent(prompt);const raw=result.response.text().replace(/```json|```/g,'').trim();const parsed=JSON.parse(raw);await Promise.all([db.from('candidates').update({ai_summary:parsed.summary}).eq('id',app.candidate_id),db.from('applications').update({match_score:Math.max(0,Math.min(100,Number(parsed.score))),match_reason:parsed.reason}).eq('id',applicationId)]);return NextResponse.json(parsed)
 }catch(e:any){return NextResponse.json({error:e.message||'Could not analyze resume'},{status:500})}
}
