'use client'
import { useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { Plus, Search, Pencil, Trash2, X, UploadCloud, Loader2, ExternalLink, MoreHorizontal } from 'lucide-react'
import { formatDate, initials } from '@/lib/utils'

export type Field={name:string,labelPt:string,labelEn:string,type?:'text'|'email'|'url'|'date'|'datetime-local'|'time'|'textarea'|'select'|'number'|'checkbox'|'file',required?:boolean,options?:{value:string,labelPt:string,labelEn:string}[],relation?:string,fileFolder?:string,uploadTarget?:string,accept?:string}
export type EntityConfig={resource:string,titlePt:string,titleEn:string,singularPt:string,singularEn:string,descriptionPt:string,descriptionEn:string,fields:Field[],primary:string,secondary?:string,dateField?:string,statusField?:string}
type Row=Record<string,any>
const formSchema=z.record(z.any())
export function EntityManager({config,lang,globalSearch='',compact=false,onChanged}:{config:EntityConfig,lang:'pt'|'en',globalSearch?:string,compact?:boolean,onChanged?:()=>void}){
 const pt=lang==='pt';const [rows,setRows]=useState<Row[]>([]);const [relations,setRelations]=useState<Record<string,Row[]>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Row|null>(null);const [search,setSearch]=useState('');const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState('');
 const {register,handleSubmit,reset,setValue,watch,formState:{errors}}=useForm<Row>({resolver:zodResolver(formSchema)})
 async function load(){setLoading(true);setError('');try{const response=await fetch(`/api/data/${config.resource}?_=${Date.now()}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setRows(body);const relationNames=[...new Set(config.fields.map(f=>f.relation).filter(Boolean))] as string[];const entries=await Promise.all(relationNames.map(async r=>{const rr=await fetch(`/api/data/${r}?_=${Date.now()}`,{cache:'no-store'});return [r,rr.ok?await rr.json():[]]}));setRelations(Object.fromEntries(entries))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[config.resource])
 const filtered=useMemo(()=>{const q=(globalSearch||search).toLowerCase();return !q?rows:rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q))},[rows,search,globalSearch])
 function open(row?:Row){setEditing(row||null);reset(row||Object.fromEntries(config.fields.map(f=>[f.name,f.type==='checkbox'?false:''])));setModal(true)}
 async function submit(values:Row){setSaving(true);setError('');try{const response=await fetch(`/api/data/${config.resource}`,{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(editing?{...values,id:editing.id}:values)});const body=await response.json();if(!response.ok)throw new Error(body.error);setModal(false);await load();onChanged?.()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function remove(row:Row){if(!confirm(pt?`Excluir “${row[config.primary]}”? Esta ação não pode ser desfeita.`:`Delete “${row[config.primary]}”? This cannot be undone.`))return;const r=await fetch(`/api/data/${config.resource}?id=${row.id}`,{method:'DELETE'});const b=await r.json();if(!r.ok)setError(b.error);else{load();onChanged?.()}}
 async function upload(file:File,field:Field){setUploading(field.name);try{const form=new FormData();form.append('file',file);form.append('folder',field.fileFolder||config.resource);const r=await fetch('/api/upload',{method:'POST',body:form,cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error);const target=field.uploadTarget||field.name;setValue(target,b.url,{shouldDirty:true});if(config.fields.some(f=>f.name===target.replace('_url','_path')))setValue(target.replace('_url','_path'),b.path)}catch(e:any){setError(e.message)}finally{setUploading('')}}
 function relationLabel(item:Row,relation=''){if(item._label)return item._label;if(item.candidates?.name||item.jobs?.title)return `${item.candidates?.name||''}${item.jobs?.title?' · '+item.jobs.title:''}`;if(item.employees?.name||item.trainings?.name)return `${item.employees?.name||''}${item.trainings?.name?' · '+item.trainings.name:''}`;return item.name||item.title||item.email||`${relation.replaceAll('_',' ')} ${String(item.id||'').slice(0,8)}`}
 function display(field:string,value:any){const f=config.fields.find(x=>x.name===field);if(!value)return '—';if(f?.relation){const item=relations[f.relation]?.find(x=>x.id===value);return item?relationLabel(item,f.relation):value.slice?.(0,8)||value}if(f?.type==='date'||f?.type==='datetime-local')return formatDate(value,pt?'pt-BR':'en-US');if(typeof value==='boolean')return value?(pt?'Sim':'Yes'):(pt?'Não':'No');return String(value)}
 return <section className={compact?'entity compact':'entity'}><header className="entity-head"><div><span>{config.resource.replaceAll('_',' ').toUpperCase()}</span><h2>{pt?config.titlePt:config.titleEn}</h2><p>{pt?config.descriptionPt:config.descriptionEn}</p></div><div className="entity-actions">{!globalSearch&&<label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={pt?'Buscar…':'Search…'}/></label>}<button className="primary" onClick={()=>open()}><Plus/>{pt?`Novo ${config.singularPt}`:`New ${config.singularEn}`}</button></div></header>{error&&<div className="error-banner"><span>{error}</span><button onClick={()=>setError('')}><X/></button></div>}{loading?<div className="table-state"><Loader2 className="spin"/>{pt?'Carregando…':'Loading…'}</div>:filtered.length===0?<div className="empty-state"><span>{initials(config.singularPt)}</span><h3>{pt?'Nenhum registro encontrado':'No records found'}</h3><p>{pt?'Comece adicionando o primeiro registro. Os dados serão salvos no Supabase.':'Add your first record. Data will be saved to Supabase.'}</p><button onClick={()=>open()}><Plus/>{pt?'Adicionar agora':'Add now'}</button></div>:<div className="data-list">{filtered.map(row=><article key={row.id} className="data-row"><span className="person-avatar">{row.photo_url?<img src={row.photo_url} alt=""/>:initials(String(row[config.primary]||config.singularPt))}</span><div className="row-main"><strong>{display(config.primary,row[config.primary])}</strong><small>{config.secondary?display(config.secondary,row[config.secondary]):formatDate(row.created_at,pt?'pt-BR':'en-US')}</small></div>{config.dateField&&<div className="row-meta"><span>{pt?'Data':'Date'}</span><b>{display(config.dateField,row[config.dateField])}</b></div>}{config.statusField&&<span className={`status-pill status-${row[config.statusField]}`}>{String(row[config.statusField]||'—')}</span>}<div className="row-actions"><button onClick={()=>open(row)} title={pt?'Editar':'Edit'}><Pencil/></button><button onClick={()=>remove(row)} title={pt?'Excluir':'Delete'}><Trash2/></button><button className="more"><MoreHorizontal/></button></div></article>)}</div>}
 {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setModal(false)}}><section className="modal" role="dialog" aria-modal="true"><header><div><span>{editing?(pt?'EDITAR REGISTRO':'EDIT RECORD'):(pt?'NOVO REGISTRO':'NEW RECORD')}</span><h2>{editing?display(config.primary,editing[config.primary]):(pt?config.singularPt:config.singularEn)}</h2></div><button onClick={()=>setModal(false)}><X/></button></header><form onSubmit={handleSubmit(submit)}><div className="form-grid">{config.fields.map(field=><label key={field.name} className={field.type==='textarea'||field.type==='file'?'wide':''}><span>{pt?field.labelPt:field.labelEn}{field.required&&' *'}</span>{field.type==='textarea'?<textarea {...register(field.name,{required:field.required})} rows={4}/>:field.type==='select'?<select {...register(field.name,{required:field.required})}><option value="">{pt?'Selecione…':'Select…'}</option>{field.options?.map(o=><option key={o.value} value={o.value}>{pt?o.labelPt:o.labelEn}</option>)}{field.relation&&relations[field.relation]?.filter(item=>item.id!==editing?.id).map(item=><option key={item.id} value={item.id}>{relationLabel(item,field.relation)}</option>)}</select>:field.type==='checkbox'?<span className="checkbox"><input type="checkbox" {...register(field.name)}/>{pt?'Sim':'Yes'}</span>:field.type==='file'?<><span className="file-input"><UploadCloud/>{uploading===field.name?(pt?'Enviando…':'Uploading…'):(pt?'Selecionar arquivo':'Choose file')}<input type="file" accept={field.accept||'.pdf,image/png,image/jpeg,image/webp'} disabled={!!uploading} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],field)}/></span>{watch(field.uploadTarget||field.name)&&<a className="file-link" href={watch(field.uploadTarget||field.name)} target="_blank"><ExternalLink/>{pt?'Arquivo enviado':'Uploaded file'}</a>}<input type="hidden" {...register(field.name)}/></>:<input type={field.type||'text'} {...register(field.name,{required:field.required,valueAsNumber:field.type==='number'})}/>} {errors[field.name]&&<small>{pt?'Campo obrigatório':'Required field'}</small>}</label>)}</div><footer><button type="button" onClick={()=>setModal(false)}>{pt?'Cancelar':'Cancel'}</button><button className="primary" disabled={saving}>{saving&&<Loader2 className="spin"/>}{saving?(pt?'Salvando…':'Saving…'):(pt?'Salvar alterações':'Save changes')}</button></footer></form></section></div>}</section>
}
