'use client'
import { useEffect, useState } from 'react'
import { EntityManager, type EntityConfig } from './entity-manager'
import { PublicationHub } from './publication-hub'
import { Building2, Network, Sparkles, Video, Loader2, ArrowRight } from 'lucide-react'

const status=(values:string[])=>values.map(value=>({value,labelPt:({active:'Ativo',inactive:'Inativo',draft:'Rascunho',closed:'Encerrado',completed:'Concluído',paused:'Pausado',pending:'Pendente',approved:'Aprovado',rejected:'Recusado',open:'Aberta',screening:'Triagem',interview:'Entrevista',offer:'Oferta',hired:'Contratado',in_progress:'Em andamento',expired:'Vencido',scheduled:'Agendada',cancelled:'Cancelada',full_time:'Tempo integral',part_time:'Meio período',contract:'Contrato',internship:'Estágio',remote:'Remoto',hybrid:'Híbrido',onsite:'Presencial',preboarding:'Pré-onboarding',week1:'Primeira semana',day30:'30 dias',day60:'60 dias',day90:'90 dias',scale:'Escala',text:'Texto',self:'Autoavaliação',peer:'Colega',manager:'Gestor',submitted:'Enviada',vacation:'Férias',day_off:'Folga',sick:'Saúde',other:'Outro'} as any)[value]||value,labelEn:value.replace('_',' ')}))
const configs:Record<string,EntityConfig>={
 employees:{resource:'employees',titlePt:'Diretório de funcionários',titleEn:'Employee directory',singularPt:'funcionário',singularEn:'employee',descriptionPt:'Pessoas, cargos e estrutura organizacional.',descriptionEn:'People, roles and organizational structure.',primary:'name',secondary:'job_title',dateField:'hire_date',statusField:'status',fields:[{name:'name',labelPt:'Nome completo',labelEn:'Full name',required:true},{name:'job_title',labelPt:'Cargo',labelEn:'Job title',required:true},{name:'department_id',labelPt:'Departamento',labelEn:'Department',type:'select',relation:'departments'},{name:'email',labelPt:'E-mail',labelEn:'Email',type:'email',required:true},{name:'phone',labelPt:'Telefone',labelEn:'Phone'},{name:'birth_date',labelPt:'Data de nascimento',labelEn:'Birth date',type:'date'},{name:'hire_date',labelPt:'Data de admissão',labelEn:'Hire date',type:'date',required:true},{name:'photo_url',labelPt:'Link da foto de perfil',labelEn:'Profile photo URL',type:'url'},{name:'photo_upload',labelPt:'Ou enviar foto do dispositivo',labelEn:'Or upload a profile photo',type:'file',fileFolder:'profiles',uploadTarget:'photo_url',accept:'image/png,image/jpeg,image/webp'},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',required:true,options:status(['active','inactive'])},{name:'manager_id',labelPt:'Gestor direto',labelEn:'Direct manager',type:'select',relation:'employees'}]},
 departments:{resource:'departments',titlePt:'Departamentos',titleEn:'Departments',singularPt:'departamento',singularEn:'department',descriptionPt:'Organize áreas e hierarquias.',descriptionEn:'Organize teams and hierarchy.',primary:'name',secondary:'description',fields:[{name:'name',labelPt:'Nome',labelEn:'Name',required:true},{name:'description',labelPt:'Descrição',labelEn:'Description',type:'textarea'},{name:'parent_id',labelPt:'Departamento superior',labelEn:'Parent department',type:'select',relation:'departments'}]},
 onboarding_templates:{resource:'onboarding_templates',titlePt:'Templates de onboarding',titleEn:'Onboarding templates',singularPt:'template',singularEn:'template',descriptionPt:'Jornadas reutilizáveis para novas contratações.',descriptionEn:'Reusable journeys for new hires.',primary:'name',secondary:'description',fields:[{name:'name',labelPt:'Nome',labelEn:'Name',required:true},{name:'description',labelPt:'Descrição',labelEn:'Description',type:'textarea'}]},
 onboarding_template_tasks:{resource:'onboarding_template_tasks',titlePt:'Tarefas dos templates',titleEn:'Template tasks',singularPt:'tarefa',singularEn:'task',descriptionPt:'Configure tarefas por fase da jornada.',descriptionEn:'Configure tasks by journey phase.',primary:'title',secondary:'phase',fields:[{name:'template_id',labelPt:'Template',labelEn:'Template',type:'select',relation:'onboarding_templates',required:true},{name:'title',labelPt:'Tarefa',labelEn:'Task',required:true},{name:'phase',labelPt:'Fase',labelEn:'Phase',type:'select',required:true,options:status(['preboarding','week1','day30','day60','day90'])},{name:'position',labelPt:'Ordem',labelEn:'Order',type:'number'}]},
 onboardings:{resource:'onboardings',titlePt:'Onboardings em andamento',titleEn:'Active onboardings',singularPt:'onboarding',singularEn:'onboarding',descriptionPt:'Acompanhe cada nova contratação.',descriptionEn:'Track every new hire journey.',primary:'employee_id',secondary:'template_id',dateField:'start_date',statusField:'status',fields:[{name:'employee_id',labelPt:'Funcionário',labelEn:'Employee',type:'select',relation:'employees',required:true},{name:'template_id',labelPt:'Template',labelEn:'Template',type:'select',relation:'onboarding_templates'},{name:'start_date',labelPt:'Data inicial',labelEn:'Start date',type:'date',required:true},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',required:true,options:status(['active','completed','paused'])}]},
 onboarding_tasks:{resource:'onboarding_tasks',titlePt:'Checklist individual',titleEn:'Individual checklist',singularPt:'tarefa',singularEn:'task',descriptionPt:'Conclua e acompanhe tarefas de cada onboarding.',descriptionEn:'Complete and track onboarding tasks.',primary:'title',secondary:'phase',dateField:'due_date',statusField:'completed',fields:[{name:'onboarding_id',labelPt:'Onboarding',labelEn:'Onboarding',type:'select',relation:'onboardings',required:true},{name:'title',labelPt:'Tarefa',labelEn:'Task',required:true},{name:'phase',labelPt:'Fase',labelEn:'Phase',type:'select',options:status(['preboarding','week1','day30','day60','day90']),required:true},{name:'due_date',labelPt:'Prazo',labelEn:'Due date',type:'date'},{name:'completed',labelPt:'Concluída',labelEn:'Completed',type:'checkbox'},{name:'completed_at',labelPt:'Concluída em',labelEn:'Completed at',type:'datetime-local'}]},
 review_cycles:{resource:'review_cycles',titlePt:'Ciclos de avaliação',titleEn:'Review cycles',singularPt:'ciclo',singularEn:'cycle',descriptionPt:'Planeje períodos de avaliação 360°.',descriptionEn:'Plan 360° review periods.',primary:'name',secondary:'status',dateField:'start_date',statusField:'status',fields:[{name:'name',labelPt:'Nome',labelEn:'Name',required:true},{name:'start_date',labelPt:'Início',labelEn:'Starts',type:'date',required:true},{name:'end_date',labelPt:'Fim',labelEn:'Ends',type:'date',required:true},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',options:status(['draft','active','closed']),required:true}]},
 review_questions:{resource:'review_questions',titlePt:'Perguntas configuráveis',titleEn:'Configurable questions',singularPt:'pergunta',singularEn:'question',descriptionPt:'Defina escalas e perguntas abertas.',descriptionEn:'Define rating scales and open questions.',primary:'prompt',secondary:'question_type',fields:[{name:'cycle_id',labelPt:'Ciclo',labelEn:'Cycle',type:'select',relation:'review_cycles',required:true},{name:'prompt',labelPt:'Pergunta',labelEn:'Question',type:'textarea',required:true},{name:'question_type',labelPt:'Tipo',labelEn:'Type',type:'select',options:status(['scale','text']),required:true},{name:'position',labelPt:'Ordem',labelEn:'Order',type:'number'}]},
 reviews:{resource:'reviews',titlePt:'Avaliações 360°',titleEn:'360° reviews',singularPt:'avaliação',singularEn:'review',descriptionPt:'Registre avaliações self, peer e manager.',descriptionEn:'Record self, peer and manager reviews.',primary:'employee_id',secondary:'review_type',statusField:'status',fields:[{name:'cycle_id',labelPt:'Ciclo',labelEn:'Cycle',type:'select',relation:'review_cycles',required:true},{name:'employee_id',labelPt:'Avaliado',labelEn:'Employee',type:'select',relation:'employees',required:true},{name:'reviewer_id',labelPt:'Avaliador',labelEn:'Reviewer',type:'select',relation:'employees'},{name:'review_type',labelPt:'Tipo',labelEn:'Type',type:'select',options:status(['self','peer','manager']),required:true},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',options:status(['pending','submitted']),required:true},{name:'responses',labelPt:'Respostas (JSON)',labelEn:'Responses (JSON)',type:'textarea'},{name:'ai_summary',labelPt:'Resumo da IA',labelEn:'AI summary',type:'textarea'}]},
 shifts:{resource:'shifts',titlePt:'Turnos',titleEn:'Shifts',singularPt:'turno',singularEn:'shift',descriptionPt:'Cadastre horários de trabalho.',descriptionEn:'Create work schedules.',primary:'name',secondary:'start_time',fields:[{name:'name',labelPt:'Nome',labelEn:'Name',required:true},{name:'start_time',labelPt:'Início',labelEn:'Starts',type:'time',required:true},{name:'end_time',labelPt:'Fim',labelEn:'Ends',type:'time',required:true},{name:'color',labelPt:'Cor (hex)',labelEn:'Color (hex)'}]},
 shift_assignments:{resource:'shift_assignments',titlePt:'Calendário de escalas',titleEn:'Shift calendar',singularPt:'escala',singularEn:'assignment',descriptionPt:'Associe pessoas, turnos e datas.',descriptionEn:'Assign people, shifts and dates.',primary:'employee_id',secondary:'shift_id',dateField:'shift_date',fields:[{name:'employee_id',labelPt:'Funcionário',labelEn:'Employee',type:'select',relation:'employees',required:true},{name:'shift_id',labelPt:'Turno',labelEn:'Shift',type:'select',relation:'shifts',required:true},{name:'shift_date',labelPt:'Data',labelEn:'Date',type:'date',required:true},{name:'notes',labelPt:'Notas',labelEn:'Notes',type:'textarea'}]},
 leave_requests:{resource:'leave_requests',titlePt:'Folgas e férias',titleEn:'Time off requests',singularPt:'solicitação',singularEn:'request',descriptionPt:'Crie, aprove ou recuse solicitações.',descriptionEn:'Create, approve or reject requests.',primary:'employee_id',secondary:'leave_type',dateField:'start_date',statusField:'status',fields:[{name:'employee_id',labelPt:'Funcionário',labelEn:'Employee',type:'select',relation:'employees',required:true},{name:'leave_type',labelPt:'Tipo',labelEn:'Type',type:'select',options:status(['vacation','day_off','sick','other']),required:true},{name:'start_date',labelPt:'Início',labelEn:'Starts',type:'date',required:true},{name:'end_date',labelPt:'Fim',labelEn:'Ends',type:'date',required:true},{name:'reason',labelPt:'Motivo',labelEn:'Reason',type:'textarea'},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',options:status(['pending','approved','rejected']),required:true}]},
 jobs:{resource:'jobs',titlePt:'Vagas',titleEn:'Jobs',singularPt:'vaga',singularEn:'job',descriptionPt:'Gerencie posições e publique em múltiplos canais.',descriptionEn:'Manage positions and publish across channels.',primary:'title',secondary:'location',statusField:'status',fields:[{name:'title',labelPt:'Título da vaga',labelEn:'Job title',required:true},{name:'description',labelPt:'Missão e responsabilidades',labelEn:'Mission and responsibilities',type:'textarea',required:true},{name:'requirements',labelPt:'Requisitos',labelEn:'Requirements',type:'textarea'},{name:'location',labelPt:'Cidade / localização',labelEn:'Location'},{name:'employment_type',labelPt:'Tipo de contrato',labelEn:'Employment type',type:'select',options:status(['full_time','part_time','contract','internship'])},{name:'work_model',labelPt:'Modelo de trabalho',labelEn:'Work model',type:'select',options:status(['remote','hybrid','onsite'])},{name:'salary_range',labelPt:'Faixa salarial',labelEn:'Salary range'},{name:'department_id',labelPt:'Departamento',labelEn:'Department',type:'select',relation:'departments',required:true},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',options:status(['open','closed']),required:true}]},
 candidates:{resource:'candidates',titlePt:'Banco de candidatos',titleEn:'Candidate directory',singularPt:'candidato',singularEn:'candidate',descriptionPt:'Perfis e currículos armazenados com segurança.',descriptionEn:'Profiles and securely stored resumes.',primary:'name',secondary:'email',fields:[{name:'name',labelPt:'Nome',labelEn:'Name',required:true},{name:'email',labelPt:'E-mail',labelEn:'Email',type:'email',required:true},{name:'phone',labelPt:'Telefone',labelEn:'Phone'},{name:'resume_url',labelPt:'Currículo em PDF',labelEn:'PDF resume',type:'file',fileFolder:'resumes',accept:'application/pdf'},{name:'ai_summary',labelPt:'Resumo da IA',labelEn:'AI summary',type:'textarea'}]},
 applications:{resource:'applications',titlePt:'Pipeline de candidaturas',titleEn:'Application pipeline',singularPt:'candidatura',singularEn:'application',descriptionPt:'Mova candidatos entre as etapas do processo.',descriptionEn:'Move candidates through your hiring process.',primary:'candidate_id',secondary:'job_id',statusField:'stage',fields:[{name:'candidate_id',labelPt:'Candidato',labelEn:'Candidate',type:'select',relation:'candidates',required:true},{name:'job_id',labelPt:'Vaga',labelEn:'Job',type:'select',relation:'jobs',required:true},{name:'stage',labelPt:'Etapa',labelEn:'Stage',type:'select',options:status(['screening','interview','offer','hired','rejected']),required:true},{name:'match_score',labelPt:'Score de match',labelEn:'Match score',type:'number'},{name:'match_reason',labelPt:'Justificativa',labelEn:'Reason',type:'textarea'},{name:'notes',labelPt:'Notas',labelEn:'Notes',type:'textarea'}]},
 interviews:{resource:'interviews',titlePt:'Entrevistas',titleEn:'Interviews',singularPt:'entrevista',singularEn:'interview',descriptionPt:'Agenda, links e notas de entrevistas.',descriptionEn:'Interview schedule, links and notes.',primary:'application_id',secondary:'status',dateField:'scheduled_at',statusField:'status',fields:[{name:'application_id',labelPt:'Candidatura',labelEn:'Application',type:'select',relation:'applications',required:true},{name:'scheduled_at',labelPt:'Data e hora',labelEn:'Date and time',type:'datetime-local',required:true},{name:'interviewer_id',labelPt:'Entrevistador',labelEn:'Interviewer',type:'select',relation:'employees'},{name:'meeting_link',labelPt:'Link da reunião',labelEn:'Meeting link'},{name:'notes',labelPt:'Notas',labelEn:'Notes',type:'textarea'},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',options:status(['scheduled','completed','cancelled']),required:true}]},
 trainings:{resource:'trainings',titlePt:'Programas de treinamento',titleEn:'Training programs',singularPt:'treinamento',singularEn:'training',descriptionPt:'Conteúdos, obrigatoriedade e validade.',descriptionEn:'Programs, requirements and validity.',primary:'name',secondary:'category',fields:[{name:'name',labelPt:'Nome',labelEn:'Name',required:true},{name:'category',labelPt:'Categoria',labelEn:'Category',required:true},{name:'mandatory',labelPt:'Obrigatório',labelEn:'Mandatory',type:'checkbox'},{name:'validity_days',labelPt:'Validade (dias)',labelEn:'Validity (days)',type:'number'},{name:'description',labelPt:'Descrição',labelEn:'Description',type:'textarea'}]},
 training_enrollments:{resource:'training_enrollments',titlePt:'Matrículas e certificados',titleEn:'Enrollments & certificates',singularPt:'matrícula',singularEn:'enrollment',descriptionPt:'Acompanhe conclusão, validade e certificados.',descriptionEn:'Track completion, validity and certificates.',primary:'employee_id',secondary:'training_id',dateField:'due_date',statusField:'status',fields:[{name:'training_id',labelPt:'Treinamento',labelEn:'Training',type:'select',relation:'trainings',required:true},{name:'employee_id',labelPt:'Funcionário',labelEn:'Employee',type:'select',relation:'employees',required:true},{name:'assigned_at',labelPt:'Matrícula em',labelEn:'Assigned at',type:'date',required:true},{name:'due_date',labelPt:'Prazo',labelEn:'Due date',type:'date'},{name:'completed_at',labelPt:'Conclusão',labelEn:'Completed at',type:'date'},{name:'expires_at',labelPt:'Validade',labelEn:'Expires at',type:'date'},{name:'status',labelPt:'Status',labelEn:'Status',type:'select',options:status(['pending','in_progress','completed','expired']),required:true},{name:'certificate_url',labelPt:'Certificado',labelEn:'Certificate',type:'file',fileFolder:'certificates'}]}
}
const sections:Record<string,string[]>={employees:['employees','departments'],onboarding:['onboardings','onboarding_tasks','onboarding_templates','onboarding_template_tasks'],performance:['review_cycles','review_questions','reviews'],attendance:['shift_assignments','leave_requests','shifts'],recruitment:['publications','applications','jobs','candidates','interviews'],training:['training_enrollments','trainings']}
export function ModuleView({section,lang,search}:{section:string,lang:'pt'|'en',search:string}){const tabs=sections[section]||sections.employees;const [tab,setTab]=useState(tabs[0]);useEffect(()=>setTab(tabs[0]),[section]);const pt=lang==='pt';const tabName=(item:string)=>item==='publications'?(pt?'Publicar em portais':'Publish to portals'):(pt?configs[item].titlePt:configs[item].titleEn);return <div className="module-page">{section==='recruitment'&&<div className="meet-banner"><div><Video/><span><strong>{pt?'Agenda inteligente de entrevistas':'Smart interview scheduling'}</strong><small>{pt?'Crie a sala e registre a entrevista em um único fluxo.':'Create the room and save the interview in one flow.'}</small></span></div><a href="https://meet.google.com/new" target="_blank">{pt?'Nova reunião':'New meeting'}<ArrowRight/></a></div>}<nav className="tabs" data-tour={section==='recruitment'?'recruitment-tabs':undefined} aria-label="Module sections">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?'active':''}>{tabName(item)}</button>)}</nav>{tab==='employees'&&<OrgSnapshot lang={lang}/>} {tab==='reviews'&&<ReviewAi lang={lang}/>} {tab==='shift_assignments'&&<MonthCalendar lang={lang}/>} {tab==='interviews'&&<InterviewScheduler lang={lang}/>} {tab==='publications'?<PublicationHub lang={lang} onEditJob={()=>setTab('jobs')}/>:tab==='applications'?<><ApplicationKanban lang={lang}/><EntityManager config={configs[tab]} lang={lang} globalSearch={search}/></>:<EntityManager config={configs[tab]} lang={lang} globalSearch={search}/>}</div>}
function ApplicationKanban({ lang }: { lang: 'pt'|'en' }) {
  const [rows, setRows] = useState<any[]>([])
  const [people, setPeople] = useState<any[]>([])
  const [jobs, setJobs] = useState<any[]>([])
  const [busy, setBusy] = useState('')
  const [insight, setInsight] = useState<{ name: string, score?: number, summary: string, error?: boolean } | null>(null)
  const stages = ['screening','interview','offer','hired','rejected']
  const pt = lang === 'pt'
  const load = () => Promise.all(['applications','candidates','jobs'].map(resource => fetch(`/api/data/${resource}?_=${Date.now()}`, { cache: 'no-store' }).then(response => response.ok ? response.json() : []))).then(([applications,candidates,openJobs]) => { setRows(applications); setPeople(candidates); setJobs(openJobs) })
  useEffect(() => { void load() }, [])

  async function move(id: string, stage: string) {
    setBusy(id)
    setInsight(null)
    const response = await fetch('/api/data/applications', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, stage }) })
    if (!response.ok) setInsight({ name: pt ? 'Falha ao mover candidatura' : 'Could not move application', summary: (await response.json()).error, error: true })
    await load()
    setBusy('')
  }

  async function analyze(row: any) {
    setBusy(row.id)
    setInsight(null)
    const response = await fetch('/api/ai/resume', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ applicationId: row.id }) })
    const body = await response.json()
    const name = people.find(person => person.id === row.candidate_id)?.name || (pt ? 'Candidato' : 'Candidate')
    setInsight(response.ok ? { name, score: body.score, summary: body.summary } : { name, summary: body.error, error: true })
    await load()
    setBusy('')
  }

  return <section className="kanban"><header><div><span>SMART ATS</span><h2>{pt ? 'Pipeline inteligente de talentos' : 'Smart talent pipeline'}</h2><p>{pt ? 'Avance etapas e compare currículos sem sair do fluxo.' : 'Move stages and compare resumes without leaving the flow.'}</p></div><Sparkles/></header>
    {insight && <div className={`ats-insight${insight.error ? ' error' : ''}`}><span><Sparkles/></span><div><small>{insight.error ? (pt ? 'ATENÇÃO' : 'NOTICE') : 'GEMINI MATCH'}</small><h3>{insight.name}{insight.score != null && <b>{insight.score}/100</b>}</h3><p>{insight.summary}</p></div><button onClick={() => setInsight(null)}>×</button></div>}
    <div className="kanban-scroll">{stages.map(stage => <div className="kanban-column" key={stage}><h3><i/>{status([stage])[0][pt ? 'labelPt' : 'labelEn']}<b>{rows.filter(row => row.stage === stage).length}</b></h3>{rows.filter(row => row.stage === stage).map(row => <article key={row.id}><strong>{people.find(person => person.id === row.candidate_id)?.name || '—'}</strong><small>{jobs.find(job => job.id === row.job_id)?.title || '—'}</small>{row.match_score != null && <span className="score">{row.match_score}% match</span>}<footer><select value={row.stage} disabled={busy === row.id} onChange={event => move(row.id,event.target.value)}>{stages.map(value => <option key={value} value={value}>{status([value])[0][pt ? 'labelPt' : 'labelEn']}</option>)}</select><button disabled={busy === row.id} onClick={() => analyze(row)}>{busy === row.id ? <Loader2 className="spin"/> : <Sparkles/>}{pt ? 'Match IA' : 'AI match'}</button></footer></article>)}</div>)}</div>
  </section>
}

function OrgSnapshot({lang}:{lang:'pt'|'en'}){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{fetch(`/api/data/employees?_=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(setRows)},[]);const roots=rows.filter(x=>!x.manager_id||!rows.some(y=>y.id===x.manager_id));const pt=lang==='pt';function Node({person,depth=0}:{person:any,depth?:number}){const children=rows.filter(x=>x.manager_id===person.id);return <div className="org-node" style={{marginLeft:depth*22}}><span>{person.name}</span><small>{person.job_title}</small>{children.map(c=><Node key={c.id} person={c} depth={depth+1}/>)}</div>}if(!rows.length)return null;return <section className="insight-card"><header><Network/><div><span>{pt?'ESTRUTURA':'STRUCTURE'}</span><h2>{pt?'Organograma':'Organization chart'}</h2></div></header><div className="org-tree">{roots.map(r=><Node key={r.id} person={r}/>)}</div></section>}

function ReviewAi({lang}:{lang:'pt'|'en'}){const [employees,setEmployees]=useState<any[]>([]);const [cycles,setCycles]=useState<any[]>([]);const [employeeId,setEmployeeId]=useState('');const [cycleId,setCycleId]=useState('');const [summary,setSummary]=useState('');const [loading,setLoading]=useState(false);const pt=lang==='pt';useEffect(()=>{Promise.all(['employees','review_cycles'].map(r=>fetch(`/api/data/${r}?_=${Date.now()}`,{cache:'no-store'}).then(x=>x.ok?x.json():[]))).then(([e,c])=>{setEmployees(e);setCycles(c)})},[]);async function generate(){if(!employeeId||!cycleId)return;setLoading(true);setSummary('');const r=await fetch('/api/ai/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employeeId,cycleId})});const b=await r.json();setSummary(r.ok?b.summary:b.error);setLoading(false)}return <section className="insight-card ai-card"><header><Sparkles/><div><span>GEMINI FLASH</span><h2>{pt?'Resumo inteligente 360°':'AI 360° summary'}</h2></div></header><div className="ai-controls"><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">{pt?'Selecione o funcionário':'Select employee'}</option>{employees.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select value={cycleId} onChange={e=>setCycleId(e.target.value)}><option value="">{pt?'Selecione o ciclo':'Select cycle'}</option>{cycles.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><button onClick={generate} disabled={loading||!employeeId||!cycleId}>{loading?<Loader2 className="spin"/>:<Sparkles/>}{pt?'Gerar resumo':'Generate summary'}</button></div>{summary&&<p className="ai-result">{summary}</p>}</section>}

function MonthCalendar({lang}:{lang:'pt'|'en'}){const [items,setItems]=useState<any[]>([]);useEffect(()=>{fetch(`/api/data/shift_assignments?_=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(setItems)},[]);const now=new Date();const first=new Date(now.getFullYear(),now.getMonth(),1);const offset=first.getDay();const total=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const days=Array.from({length:offset+total},(_,i)=>i<offset?null:i-offset+1);const pt=lang==='pt';return <section className="insight-card calendar-card"><header><Building2/><div><span>{pt?'MÊS ATUAL':'CURRENT MONTH'}</span><h2>{new Intl.DateTimeFormat(pt?'pt-BR':'en-US',{month:'long',year:'numeric'}).format(now)}</h2></div></header><div className="mini-calendar"><div className="weekdays">{(pt?['D','S','T','Q','Q','S','S']:['S','M','T','W','T','F','S']).map((d,i)=><b key={i}>{d}</b>)}</div><div className="calendar-days">{days.map((day,i)=><span key={i} className={day===now.getDate()?'today':''}>{day}{day&&items.some(x=>new Date(`${x.shift_date}T12:00:00`).getDate()===day)&&<i/>}</span>)}</div></div></section>}

function InterviewScheduler({lang}:{lang:'pt'|'en'}){const pt=lang==='pt';const [applications,setApplications]=useState<any[]>([]);const [employees,setEmployees]=useState<any[]>([]);const [form,setForm]=useState({application_id:'',scheduled_at:'',interviewer_id:'',meeting_link:'',notes:'',status:'scheduled'});const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>{Promise.all(['applications','employees'].map(r=>fetch(`/api/data/${r}?_=${Date.now()}`,{cache:'no-store'}).then(x=>x.ok?x.json():[]))).then(([a,e])=>{setApplications(a);setEmployees(e)})},[]);async function schedule(){if(!form.application_id||!form.scheduled_at)return;setSaving(true);setMessage('');const r=await fetch('/api/data/interviews',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form),cache:'no-store'});const b=await r.json();setMessage(r.ok?(pt?'Entrevista agendada com sucesso.':'Interview scheduled successfully.'):b.error);setSaving(false);if(r.ok)setForm({...form,scheduled_at:'',notes:''})}return <section className="insight-card scheduler-card"><header><Video/><div><span>{pt?'AGENDA RÁPIDA':'QUICK SCHEDULING'}</span><h2>{pt?'Agendar entrevista':'Schedule interview'}</h2></div></header><div className="scheduler-grid"><select value={form.application_id} onChange={e=>setForm({...form,application_id:e.target.value})}><option value="">{pt?'Selecione a candidatura':'Select application'}</option>{applications.map(a=><option key={a.id} value={a.id}>{a.candidates?.name||a.id.slice(0,8)} · {a.jobs?.title||''}</option>)}</select><input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/><select value={form.interviewer_id} onChange={e=>setForm({...form,interviewer_id:e.target.value})}><option value="">{pt?'Entrevistador opcional':'Optional interviewer'}</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><input type="url" placeholder={pt?'Cole o link do Google Meet':'Paste Google Meet link'} value={form.meeting_link} onChange={e=>setForm({...form,meeting_link:e.target.value})}/><a href="https://meet.google.com/new" target="_blank"><Video/>{pt?'Criar sala no Meet':'Create Meet room'}</a><button onClick={schedule} disabled={saving||!form.application_id||!form.scheduled_at}>{saving?<Loader2 className="spin"/>:<CalendarIcon/>}{pt?'Agendar agora':'Schedule now'}</button></div>{message&&<p className="scheduler-message">{message}</p>}</section>}
function CalendarIcon(){return <span aria-hidden="true">+</span>}
